:toc:

= HomeStack Backend

== Satellite

Der Satellite ist ein Endpoint im lokalen Netz des Benutzers, um ein Monitoring zu ermöglichen.
Dieser Satellite ist jedoch von außen direkt nicht erreichbar, weshalb er über das Internet eine Websocket Verbindung aufbauen muss.
Nachdem eine Verbindung mit der Cloud hergestellt wurde, erhält der Satellite seine Konfiguration.
Anschließend weiß er, welche Geräte mit welchen Metriken und in welchen Intervallen er abfragen muss.
Sofern ein neuer Metric Record ermittelt wurde, meldet er dies der Cloud.

=== Initial Auth Flow

Damit der Satellite sicher einem User in der Cloud zugeordnet werden kann, muss sich dieser initial in der Cloud melden.
Die ID des neuen Satellites wird beim manuellen Hinzufügen generiert und automatisch validiert, sodass anschließend ein Token am Frontend angezeigt werden kann.
Beides wird dem Satellite gesetzt, sodass dieser sich an der Cloud authentifizieren kann.

[plantuml,Initial Auth Flow,svg]
....
skinparam backgroundColor #FEFEFE

|Frontend|
start
:Benutzer generiert
neuen Satellite Lease
via Frontend;
|Cloud|
:Lease wird erzeugt
und automatisch
validiert;
:Token wird generiert;
|Frontend|
:Token wird einmalig
angezeigt;
|Satellite|
:Benutzer setzt die
ID und den Token;
:Satellite öffnen beim Start
eine Websocket Verbindung
zur Cloud;
:AUTHENTICATE Event
mit "id" als Identifier
und "token" als Token;
stop
....

=== Initial Config / Renewal Flow

Um die initiale Konfiguration des Satellites zu erhalten, muss sich dieser erst gegen das Cloud-Backend authentifizieren.
So lassen sich bspw. die Satellites erst für einen bestimmten Account freischalten, um einen möglichen "Angriff" blockieren zu können.

[plantuml,Initial Config,svg]
....
skinparam backgroundColor #FEFEFE
partition Satellite {
    (*) --> "Open Websocket"
    --> Send AUTHENTICATE event
}

partition Cloud {
    --> Check Token
    if "" then
        -->[Valid] Send CONFIG event
    else
        -->[Invalid] (*)
    endif
}

partition Satellite {
    "Send CONFIG event" --> Apply Config
    -.->[renew] Send AUTHENTICATE event
}
....

