version: '3.1'
services:
  netplan-mongodb:
    image: library/mongo:4.4.1
    restart: always
    ports:
      - 127.0.0.1:27017-27019:27017-27019
    environment:
      MONGO_INITDB_ROOT_USERNAME: netplandev
      MONGO_INITDB_ROOT_PASSWORD: devlocal
      MONGO_INITDB_DATABASE: netplandev
    volumes:
      - ./data:/data/db