name: Compile / onManualRun

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Setup / Checkout
        uses: actions/checkout@v2

      - name: Setup / Maven
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: 3.6.3

      - name: Setup / JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Setup / Cache
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Setup / settings.xml
        uses: s4u/maven-settings-action@v2.2.0
        with:
          servers: '[{"id": "default", "username": "${{ secrets.nexus_user }}", "password": "${{ secrets.nexus_password }}"}]'
          mirrors: '[{"id": "default", "name": "default", "mirrorOf": "*", "url": "https://nexus.conceptive.io/repository/maven-public/"}]'

      - name: Setup / Docker Login
        uses: azure/docker-login@v1
        with:
          login-server: images.conceptive.io
          username: ${{ secrets.nexus_user }}
          password: ${{ secrets.nexus_password }}

      - name: Maven / Download Dependencies
        run: mvn -Dmaven.artifact.threads=30 -T 1C -B de.qaware.maven:go-offline-maven-plugin:1.2.8:resolve-dependencies

      - name: Native / Compile
        run: mvn clean package -Pnative -Dquarkus.container-image.build=true

      - name: Native / Integration Test
        run: mvn -Pnative test-compile failsafe:integration-test failsafe:verify

      - name: Deploy / Docker
        run: docker push images.conceptive.io/homestack.backend:latest
